### ISSUE TITLE
Every single piece of evidence needs a new variable

### ISSUE THREAD

**Issue by jbouchie** [Joryms/CMPUT250Project#2]
I THINK??

Maybe, it doesn't, but I'm pretty sure it does. Maybe.

**Comment by Jori-Romans-Student** [comment]
They will need variables yes, as the condition of these variables will dictate the rest of the game. I'll get those implemented then close the issue

**Comment by Jori-Romans-Student** [comment]
Implimented, each piece of evidence has an E: at the start of the variable name associated with it, and that variable will be a 1 if the evidence has been found
