### ISSUE TITLE
"Find Kat Dead" event needs to be paged

### ISSUE THREAD

**Issue by jbouchie** [Joryms/CMPUT250Project#3]
After the "Find Kat Dead" event, it is possible to move the player around the room and gather evidence. They player should be forced to go and interact with the closet instead of doing other stuff first.

I think this means that finding Kat's body should be paged onto the "Find Kat Dead" event and not "EV002" (interacting with the body).

**Comment by Jori-Romans-Student** [comment]
Fixed the issue by moving the event tile out of the closet so that the player can autorun onto it
