### ISSUE TITLE
Game Breaks if you want to save after leaving Kat's room

### ISSUE THREAD

**Issue by ismaeelBM** [Joryms/CMPUT250Project#33]
![image](https://user-images.githubusercontent.com/35469226/48151604-e923e300-e27e-11e8-9ea1-e3f9e72b4046.png)

![image](https://user-images.githubusercontent.com/35469226/48151611-f214b480-e27e-11e8-9ebb-0bcc1d2094bd.png)

**Comment by LeMaithy** [comment]
please be more specific?

**Comment by ismaeelBM** [comment]
When leaving kat's room after the suicide scene, when the Prompt asks do you want to save, if you click yes, the game shows an error saying failed to load (..[somedestination].../master_sheet)

**Comment by LeMaithy** [comment]
I don't know where it's getting the image from. I'm trying to find it so i can change the face to the protag's.

BUT i did fix it. I just created another file with that name. We just won't have the image of the protag for some reason.
