### ISSUE TITLE
Implement red flags (3 strikes your out)

### ISSUE THREAD

**Issue by Jori-Romans-Student** [Joryms/CMPUT250Project#8]

**Comment by Jori-Romans-Student** [comment]
Red Flag implemented for Vertical Slice 2, will need to be further worked on for Beta

**Comment by LeMaithy** [comment]
You incriminate yourself. You received 3+ “Red Flags.” At the earliest, this can happen immediately after Interview #2. If this is triggered, the game ends. You wake up to police breaking down your door. They arrest you. Your “friends” have been interrogated and all evidence points to you. After a grueling trial, you are found guilty. You go to hug your parents goodbye and you lock eyes with BB. He smiles.
